#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Xinzhu Li
url: 'https://ellelenlee.github.io'
baseurl: '/chart' #change it according to your repository name
description: A chart

